markdown: redcarpet
title: "Anima — CSS animations with a soul"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
github:
  username: "lvivski"
  project: "anima"