markdown: redcarpet
title: "Animatic — CSS animations library"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
github:
  username: "lvivski"
  project: "animatic"